// Code generated by catgen. DO NOT EDIT.

package main

type category string

var (
	categories = []string{
		"asustor_portal",
		"backup_sync",
		"blog",
		"bulletin_board",
		"business_applications",
		"content_management",
		"database",
		"download",
		"framework_library",
		"home_automation",
		"home_personal_applications",
		"media_player",
		"media_server",
		"multimedia",
		"office_productivity",
		"project_management",
		"security",
		"social_networking",
		"ticket_system",
		"utility",
		"virtualization",
		"web_hosting",
		"e_commerce",
		"e_learning",
	}
)

func (c category) ID() string {
	switch c {
	case "asustor_portal":
		return "21"
	case "backup_sync":
		return "20"
	case "blog":
		return "2"
	case "bulletin_board":
		return "3"
	case "business_applications":
		return "25"
	case "content_management":
		return "4"
	case "database":
		return "5"
	case "download":
		return "6"
	case "framework_library":
		return "18"
	case "home_automation":
		return "22"
	case "home_personal_applications":
		return "24"
	case "media_player":
		return "10"
	case "media_server":
		return "11"
	case "multimedia":
		return "13"
	case "office_productivity":
		return "14"
	case "project_management":
		return "15"
	case "security":
		return "9"
	case "social_networking":
		return "19"
	case "ticket_system":
		return "16"
	case "utility":
		return "1"
	case "virtualization":
		return "23"
	case "web_hosting":
		return "17"
	case "e_commerce":
		return "7"
	case "e_learning":
		return "8"
	default:
		panic("category " + string(c) + " does not exist")
	}
}

func (c category) Name() string {
	switch c {
	case "asustor_portal":
		return "ASUSTOR Portal"
	case "backup_sync":
		return "Backup & Sync"
	case "blog":
		return "Blog"
	case "bulletin_board":
		return "Bulletin Board"
	case "business_applications":
		return "Business Applications"
	case "content_management":
		return "Content Management"
	case "database":
		return "Database"
	case "download":
		return "Download"
	case "framework_library":
		return "Framework & Library"
	case "home_automation":
		return "Home Automation"
	case "home_personal_applications":
		return "Home/Personal Applications"
	case "media_player":
		return "Media Player"
	case "media_server":
		return "Media Server"
	case "multimedia":
		return "Multimedia"
	case "office_productivity":
		return "Office Productivity"
	case "project_management":
		return "Project Management"
	case "security":
		return "Security"
	case "social_networking":
		return "Social Networking"
	case "ticket_system":
		return "Ticket System"
	case "utility":
		return "Utility"
	case "virtualization":
		return "Virtualization"
	case "web_hosting":
		return "Web Hosting"
	case "e_commerce":
		return "eCommerce"
	case "e_learning":
		return "eLearning"
	default:
		panic("category " + string(c) + " does not exist")
	}
}
